sudo: false
language: node_js
node_js:
  - "5"

before_install:
  - if [[ `npm -v` != 3*  ]]; then npm i -g npm@3; fi

install:
  - npm install
  - npm install -g skypager-cli
script:
  - npm run test
